### ISSUE TITLE
Error while building Strapi

### ISSUE THREAD

**Issue by maximehamou** [emil-petras/strapi-regenerator#1]
Hello,
First of all, I want to thank you for your contributions!

There is an error when I run `yarn develop` after having installed and configure the plugin in Strapi (that seems be a syntax issue) :

```
Loading Strapi[ERROR]  There seems to be an unexpected error, try again with --debug for more information 
Error: Plugin name "Regenerator" is not in kebab (an-example-of-kebab-case)
```

Thank you for your help!

**Comment by emil-petras** [comment]
Solved with the fix in v0.1.4

**Comment by maximehamou** [comment]
I still have an error : `Loading Strapi [ERROR]  There seems to be an unexpected error, try again with --debug for more information Error: Error loading the plugin strapi-regenerator because strapi-regenerator is not installed. Please   ││   either install the plugin or remove its configuration. ` even if the plugin is installed.

However, I also have often this error : ` Error: Could not load js config file /Users/Maxime/Desktop/Projets_de_code/zakine-avocats.fr/backend/node_modules/strapi-blurhash/strapi-server.js: Could not load the "sharp" module using the darwin-x64 runtime`

**Comment by emil-petras** [comment]
> I still have an error : `Loading Strapi [ERROR] There seems to be an unexpected error, try again with --debug for more information Error: Error loading the plugin strapi-regenerator because strapi-regenerator is not installed. Please ││ either install the plugin or remove its configuration. ` even if the plugin is installed.
> 
> However, I also have often this error : ` Error: Could not load js config file /Users/Maxime/Desktop/Projets_de_code/zakine-avocats.fr/backend/node_modules/strapi-blurhash/strapi-server.js: Could not load the "sharp" module using the darwin-x64 runtime`

I've managed to reproduce this error and fix it. The fix is in the new version.

If the second error persists. Create an issue (with more info) in the strapi-blurhash repo.

**Comment by maximehamou** [comment]
Thank you so much! It's working perfectly!

**Comment by maximehamou** [comment]
Also, what would make the plugin perfect, would be to be able to chose the size of thumbnail generated (the output).

P.S. : I am working on it, but the output is still 32x32...

EDIT : Sorry, I just had to modify the aspect ratio while decoding the hash (I use unlazy). So nothing to change.
